// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJu3hm0JZHwMSU0d01jgnTcO16xtEVh6c',
    appId: '1:365637024668:web:72267a7bc226e77c0a6659',
    messagingSenderId: '365637024668',
    projectId: 'kkopiconnect-2f015',
    authDomain: 'kkopiconnect-2f015.firebaseapp.com',
    storageBucket: 'kkopiconnect-2f015.firebasestorage.app',
    measurementId: 'G-WFF18P93N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcoDGGi-OUDlFHZvJqVxioJHwHjsvDUM8',
    appId: '1:365637024668:android:97d38ff3785e4b280a6659',
    messagingSenderId: '365637024668',
    projectId: 'kkopiconnect-2f015',
    storageBucket: 'kkopiconnect-2f015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJUgXjHUXkManXTuCKt_qS5Gusd43kHo',
    appId: '1:365637024668:ios:55c2ed6601f72e280a6659',
    messagingSenderId: '365637024668',
    projectId: 'kkopiconnect-2f015',
    storageBucket: 'kkopiconnect-2f015.firebasestorage.app',
    iosBundleId: 'com.example.kkopiconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJUgXjHUXkManXTuCKt_qS5Gusd43kHo',
    appId: '1:365637024668:ios:55c2ed6601f72e280a6659',
    messagingSenderId: '365637024668',
    projectId: 'kkopiconnect-2f015',
    storageBucket: 'kkopiconnect-2f015.firebasestorage.app',
    iosBundleId: 'com.example.kkopiconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJu3hm0JZHwMSU0d01jgnTcO16xtEVh6c',
    appId: '1:365637024668:web:eafb1ef62ccce21e0a6659',
    messagingSenderId: '365637024668',
    projectId: 'kkopiconnect-2f015',
    authDomain: 'kkopiconnect-2f015.firebaseapp.com',
    storageBucket: 'kkopiconnect-2f015.firebasestorage.app',
    measurementId: 'G-6S940X779F',
  );
}
