// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2SlzKMedFkGAAKIRKp_Yh85ORq6CkK8',
    appId: '1:964129969682:web:c72c63bbdbc2690a1caacb',
    messagingSenderId: '964129969682',
    projectId: 'kkopiconnect',
    authDomain: 'kkopiconnect.firebaseapp.com',
    storageBucket: 'kkopiconnect.firebasestorage.app',
    measurementId: 'G-668CJELJ53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4MTki3wulJTI_iqflPOBeEO_2QRDzdA',
    appId: '1:964129969682:android:b1caf1b3920c153f1caacb',
    messagingSenderId: '964129969682',
    projectId: 'kkopiconnect',
    storageBucket: 'kkopiconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4JMkbddoXimoIFYtSpIzFTo3xAfPzrY',
    appId: '1:964129969682:ios:1d216cb165aca2f91caacb',
    messagingSenderId: '964129969682',
    projectId: 'kkopiconnect',
    storageBucket: 'kkopiconnect.firebasestorage.app',
    iosBundleId: 'com.example.kkopiconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4JMkbddoXimoIFYtSpIzFTo3xAfPzrY',
    appId: '1:964129969682:ios:1d216cb165aca2f91caacb',
    messagingSenderId: '964129969682',
    projectId: 'kkopiconnect',
    storageBucket: 'kkopiconnect.firebasestorage.app',
    iosBundleId: 'com.example.kkopiconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe2SlzKMedFkGAAKIRKp_Yh85ORq6CkK8',
    appId: '1:964129969682:web:f6ab85b04c8867b01caacb',
    messagingSenderId: '964129969682',
    projectId: 'kkopiconnect',
    authDomain: 'kkopiconnect.firebaseapp.com',
    storageBucket: 'kkopiconnect.firebasestorage.app',
    measurementId: 'G-JB5QSS3X40',
  );
}
